/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.flp.card.component;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author lfeher
 */
public class CardPanel extends javax.swing.JPanel {
    /**
     * Creates new form CardPanel
     */
    public CardPanel()  {
        initComponents();
        extra(Cards.Hearts1.getX(), Cards.Hearts1.getY(), Cards.Hearts1.getWidth(), Cards.Hearts1.getHeight());
    }
    public CardPanel(Cards c) {
        initComponents();
        extra(c.getX(), c.getY(), c.getWidth(), c.getHeight());
    }
    
    private void extra (int x, int y, int width, int height) {
        try {
            BufferedImage img = ImageIO.read(getClass().getClassLoader().getResource("org/flp/card/images/card.png"));
            img = img.getSubimage(x, y, width, height); // 500 x 500
            this.cardPicture.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            Logger.getLogger(CardPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardPicture = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cardPicture;
    // End of variables declaration//GEN-END:variables
}
